# Generated by Django 4.1.6 on 2023-03-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('education', models.CharField(max_length=20)),
                ('admission_for', models.CharField(choices=[('Play Group', 'Play Group'), ('nursery', 'nursery'), ('K.G.I', 'K.G.I'), ('K.G.II', 'K.G.II')], max_length=10)),
                ('father_name', models.CharField(max_length=50)),
                ('father_age', models.IntegerField()),
                ('father_Contact_no', models.CharField(max_length=10)),
                ('father_qualification', models.CharField(max_length=50)),
                ('father_occupation', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_age', models.IntegerField()),
                ('mother_Contact_no', models.CharField(max_length=10)),
                ('mother_qualification', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('caste_category', models.CharField(max_length=10)),
                ('student_image', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='CommonFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_form', models.PositiveIntegerField()),
                ('admission_fees', models.PositiveIntegerField()),
                ('caution_money', models.PositiveIntegerField()),
                ('id_card', models.PositiveIntegerField()),
                ('transport', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('Contact_no', models.CharField(max_length=10)),
                ('your_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('Contact_no', models.CharField(max_length=10)),
                ('suggestion', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Play Group', 'Play Group'), ('nursery', 'nursery'), ('K.G.I', 'K.G.I'), ('K.G.II', 'K.G.II')], max_length=10)),
                ('inst1', models.PositiveIntegerField()),
                ('inst2', models.PositiveIntegerField()),
                ('inst3', models.PositiveIntegerField()),
                ('inst4', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_images', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='playg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tt_pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_tt', models.CharField(max_length=20)),
                ('tt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.playg')),
            ],
        ),
        migrations.CreateModel(
            name='course_g',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coures_name', models.CharField(max_length=20)),
                ('play_g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.playg')),
            ],
        ),
    ]
