# Generated by Django 4.1.6 on 2023-03-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thrusday', 'Thrusday'), ('Friday', 'Friday')], max_length=10)),
                ('timing', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=50)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.playg')),
            ],
        ),
        migrations.DeleteModel(
            name='tt',
        ),
        migrations.DeleteModel(
            name='tt_pg',
        ),
    ]
