# Generated by Django 4.1.7 on 2023-03-15 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_timetable_delete_tt_delete_tt_pg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='father_Contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Enter only Numbers')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='father_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_Contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Enter only Numbers')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='student_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='Contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Enter only Numbers')]),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='First_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Enter only Numbers')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='full_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='playg',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Enter only Alphabets')]),
        ),
    ]
