# Generated by Django 4.1.4 on 2023-03-16 00:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_admission_father_contact_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='father_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z ]+[a-zA-Z]$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z ]+[a-zA-Z]$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='student_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z ]+[a-zA-Z]$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='First_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z ]+[a-zA-Z]$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z ]+[a-zA-Z]$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='full_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z ]+[a-zA-Z]$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.time_slot'),
        ),
    ]
